### ISSUE TITLE
Cannot extract 1440p wallpapers

### ISSUE THREAD

**Issue by larryqiann** [aiko-chan-ai/N0va-Desktop-File-Converter#2]
I'm trying to extract the 1440p version of "A Day in Monstadt" from N0va Desktop. If both versions (1080p and 1440p) have been downloaded, the 1080p video will be extracted, but the 1440p video will be missing. If the program is run on only the 1440p file, nothing is extracted.

**Comment by aiko-chan-ai** [comment]
> I'm trying to extract the 1440p version of "A Day in Monstadt" from N0va Desktop. If both versions (1080p and 1440p) have been downloaded, the 1080p video will be extracted, but the 1440p video will be missing. If the program is run on only the 1440p file, nothing is extracted.

Fixed: https://github.com/aiko-chan-ai/N0va-Desktop-File-Converter/releases/tag/1.0.1
